### ISSUE TITLE
interpretation of each metadata column

### ISSUE THREAD

**Issue by slowkow** [vijaybioinfo/COVID19_2020#2]
Could I please ask if you might be able to help me understand how to interpret the meaning of each column listed below?

By the way, is the supplement available?

---

I loaded the data like this:

```r
d <- fread("GSE152522_cd4t0n6_annotation.txt.gz")
```

### origlib

For the name `CoVi02_4_S_6_5P_Gex`, it seems that the format might be like this:

```
<orig.project_id>_<?>_<orig.peptide>_<orig.stim_time>_<?>_Gex
```

What is `4` in `4_S_6_5P`?

What is `5P` in `4_S_6_5P`?

```
> table(d$origlib, useNA = "ifany")

10x_038_BeMe03_Post_Gex  10x_038_BeMe03_Pre_Gex         BeMe04_Meta_Gex
                   7277                    9102                    5005
     BeMe04_Respiro_Gex     CoVi01_4_0_0_5P_Gex     CoVi02_4_M_6_5P_Gex
                   8392                    5831                    9379
    CoVi02_4_S_6_5P_Gex     CoVi04_4_0_0_8P_Gex     CoVi05_4_M_6_8P_Gex
                   4837                    8937                    6691
    CoVi05_4_S_6_8P_Gex     CoVi08_4_M_6_7P_Gex     CoVi08_4_S_6_7P_Gex
                   3602                    6950                    3973
    CoVi10_4_0_0_5P_Gex     CoVi11_4_M_6_5P_Gex    CoVi11_4_MS_6_4P_Gex
                   5994                    4811                   13188
    CoVi11_4_S_6_5P_Gex     CoVi14_4_M_6_8P_Gex     CoVi14_4_S_6_8P_Gex
                   1838                    4906                    1231
    CoVi16_4_M_6_9P_Gex     CoVi16_4_S_6_9P_Gex
                   8718                    2339
```

Here is `orig.donor` versus `origlib`:

![Screen Shot 2020-10-11 at 11 37 35 AM](https://user-images.githubusercontent.com/209714/95682939-35d46f00-0bb6-11eb-9fe4-8b2a43c8b7fc.png)

### orig.project_id

What is the meaning of `10x_052`?

What is the difference between `BeMe04` versus `BeMe03_038`? What is `BeMe`?

How do we interpret `CoVi01` versus `CoVi02`?

```
> table(d$orig.project_id, useNA = "ifany")

10x_052_BeMe04     BeMe03_038         CoVi01         CoVi02         CoVi04
         13397          16379           5831          14216           8937
        CoVi05         CoVi08         CoVi10         CoVi11         CoVi14
         10293          10923           5994          19837           6137
        CoVi16
         11057
```

### orig.run

Are these Illumina NovaSeq sequencing runs?

```
> table(d$orig.run, useNA = "ifany")

NV025 NV029 NV030 NV031
16379 52674 42891 11057
```

### orig.stim_time

How do we interpret the letters? 0? A? M? MS? S?

Do they correspond to peptide pools with these labels in the bioRxiv Fig 2g? How can we interpret the labels?

SARS-CoV-2
CoVs
FLU
RSV

```
> table(d$orig.stim_time, d$orig.peptide, useNA = "ifany")

        0     A     M    MS     S
  0 20762     0     0     0     0
  6     0 29776 41455 13188 17820

```

Here is Figure 1A:

![Screen Shot 2020-10-11 at 11 50 58 AM](https://user-images.githubusercontent.com/209714/95683260-11799200-0bb8-11eb-9e5a-002cdaebedd7.png)

### orig.HT_ID.global

Are the `NA` cells doublets? Or should we interpret them some other way?

```
> table(d$orig.HT_ID.global, useNA = "ifany")

Singlet    <NA>
  96268   26733

```

### orig.donor

Is there a meaning for `HT` versus `P` versus `SDBB`?

```
> table(d$orig.donor, useNA = "ifany")

   HT01    HT02    HT03    HT04     P01     P03     P04     P05     P06     P07
   3467    3373    2761    2895    1532     582     413    6429     695    3789
    P08   P0901     P10     P12     P15     P16     P17     P18     P19     P20
   1265    3934    7638    1483     132    1910    4705     668    1070    3826
    P22     P24     P25     P26     P29     P30     P31     P32     P40     P42
   5064    7629    2282     131    1746     652     163    1442    1268     425
    P43     P44     P45     P46     P47     P49     P57     P61     P64     P66
   2242    2061     228    5698     572    2445     376     317     186    2167
SDBB051 SDBB079 SDBB082 SDBB088    <NA>
   1396    1744    1687    1780   26733
```

### orig.sex

```
> table(d$orig.sex, useNA = "ifany")

Female   Male   <NA>
 35020  61248  26733
```

### orig.hospital

```
> table(d$orig.hospital, useNA = "ifany")

   No   Yes  <NA>
18655 58510 45836
```

### orig.severity

How do we interpret these coded values?

```
> table(d$orig.severity, useNA = "ifany")

  ITU  Mild  Ward  <NA>
36332 18655 22178 45836
```

**Comment by hyunhwan-jeong** [comment]
Hi, I also wonder we can have the information that @slowkow requested. 

Thank you,

Hyun-Hwan Jeong

**Comment by vijaybioinfo** [comment]
Hi,

Yes, the supplement is available as indicated in the [pre-proof](https://www.cell.com/cell/pdf/S0092-8674(20)31307-6.pdf), [here](https://data.mendeley.com/datasets/f72dhp8y6h/1).

### origlib
The format is indeed that: <orig.project_id>_<**Cell type**>_<orig.peptide>_<orig.stim_time>_<**No. of donors**>_Gex
As you can see in the heatmap, BeMe04 does not have donor hashtags.

### orig.project_id
10x_052 is just an identifier for the 10x project. Same for 10x_038.
BeMe03, BeMe04 are project/batch ID (BeMe is the first authors' initials!).

### orig.run
Yes, these are NovaSeq sequencing runs.

### orig.peptide and orig.stim_time
Yes, these are the viral peptide pools used for stimulation. As you can see with 0 (no peptide pool) being only for the unstimulated condition (0 in orig.stim_time) and the rest in the 6-hrs stimulation condition.
CoVs is the healthy donors' SARS-CoV-2-reactive cells. The supplement has more information on this.

### orig.ht_id.global
The NAs are the cells with no donor assigned because they were not hashtagged.

### orig.donor
HT just means HashTag, SDBB is San Diego BioBank, and P is just Patient. HT and SDBB are healthy people.

### orig.hospital
Yes = Hospitalised; No = Not Hospitalised.

### orig.severity
ITU: intensive treatment uni
Ward: People admitted to the hospital
Mild: Not hospitalised

Let me know if you have further questions.

Best,
Ciro
